### ISSUE TITLE
error with building picoTracker release on Ubuntu

### ISSUE THREAD

**Issue by maks** [democloid/picoTracker#1]
Apologies for opening the issue here, but the main picoTracker doesn't repo doesn't allow opening issues due to being a direct fork of the lgpt repo.

I ran into an error following the instructions on building the picoTracker "optimized build". I'm using Ubuntu 22.04 directly.

The error I get without using parallel make to help make it more clear is:
```
[ 36%] Building CXX object System/FileSystem/CMakeFiles/system_filesystem.dir/FileSystem.cpp.obj
[ 36%] Linking CXX static library libsystem_filesystem.a
[ 36%] Built target system_filesystem
Scanning dependencies of target platform_filesystem
[ 36%] Building CXX object Adapters/picoTracker/filesystem/CMakeFiles/platform_filesystem.dir/picoTrackerFileSystem.cpp.obj
/home/maks/work/picoTracker/sources/Adapters/picoTracker/filesystem/picoTrackerFileSystem.cpp:4:10: fatal error: system/Console/Trace.h: No such file or directory
    4 | #include "system/Console/Trace.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Adapters/picoTracker/filesystem/CMakeFiles/platform_filesystem.dir/build.make:76: Adapters/picoTracker/filesystem/CMakeFiles/platform_filesystem.dir/picoTrackerFileSystem.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:3029: Adapters/picoTracker/filesystem/CMakeFiles/platform_filesystem.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

I see `Trace.h` in `sources/System/Console/Trace.h` and I'm building inside a `build` dir I created off the top level as per the development doc instructions so I guess my C compiler include path isn't set quite correctly, but I'm not really sure which `CMakeLists.txt` to go digging in to check why its nto being picked up so was wondering if you've come across this before?

**Comment by democloid** [comment]
Interesting, there were some typos in imports that were not failing in OSX, no idea why. Try now, compiled fine in Debian.

**Comment by maks** [comment]
Thank you! Of course all builds fine now. 👍🏻 
And sorry for not spotting this myself, I can't believe I missed that difference in dirname case!

But I can help with explaining why you didn't see the errors on MacOS as its APFS filesystem to this day is still [case-insensitive by default](https://support.apple.com/lt-lt/guide/disk-utility/dsku19ed921c/mac).

And thanks for setting up issues on this repo! Will definitely help in the future as at very least I have a few ideas for new features and given all the great work you've already done updating the lgpt codebase, I'm planning on using it as the base to try to get lgpt working properly on the newer Opendingux linux OS versions for the rg280v devices as [currently has audio issues](https://www.youtube.com/shorts/87MJ3PwhKKY) and I've been wanting to also try to get lgpt ported to SDL2 to work better on handhelds and modern distros that dont really support SDL1.2 anymore.
