### ISSUE TITLE
Output level really low for line use

### ISSUE THREAD

**Issue by gandaja** [democloid/picoTracker#110]
Since v1.2b2

**Comment by maks** [comment]
Thanks for opening this issue. Yes this has been discussed on Discord as well. I'll start with posting a couple test builds with different settings for people to try out as the amount of reduction of output volume for different headphone/earbuds/IEMs really just needs to be a compromise setting determined experimentally.

**Comment by maks** [comment]
@gandaja not sure if you are in the discord servers @beta-testers channel so here is a test build with 1bit extra (louder) output to please test and report back on:
[picoTracker-4bit-offset.zip](https://github.com/democloid/picoTracker/files/14154917/picoTracker-4bit-offset.zip)

Please UNZIP first to get the uf2 file to install to your picoTracker.

**Comment by gandaja** [comment]
Thanks. Still haven't tried the firmware you provided, I wanted to work v1.2r2 for a few days with my headphones.
Levels are ok, but I notice a loud "pop" whenever a sample starts or finishes playing.

**Comment by gandaja** [comment]
Sorry, I've seen that a similar problem has been described in issue #67.
Will upload a zip soon.

**Comment by maks** [comment]
Fixed by #113

**Comment by maks** [comment]
I'll close this now as the remaining followup work to allow for different levels is tracked in #116

**Comment by maks** [comment]
I'll close this now as followup work for this is tracked in #117
