### ISSUE TITLE
Some samples fail to load

### ISSUE THREAD

**Issue by maks** [democloid/picoTracker#119]
I've noticed recently some samples, even fairly small ones (600kb) will fail to import/load, but only sometimes. 

I need to still come up with a way to consistently reproduce this and will then attach a minimal repro project file here.

**Comment by shockdesign** [comment]
[resampled_and_trimmed.zip](https://github.com/democloid/picoTracker/files/14216653/resampled_and_trimmed.zip)

Attaching a bunch of samples here that were taken from a unsigned 8 bit .wav, using Audacity to trim and convert them them to signed 16 bit little endian .wav files.

I can load the first 7 files and then the 8th one crashes (CymA808DecayC01.wav).. kill device, it saved the project and when loading freezes at the same place.

Note, can load this sample first...

**Comment by maks** [comment]
I started debugging this a little bit as part of working on another issue and noticed it doesn't seem to be related to file sizes but rather the number of samples being imported one after another. Will need to do some more debugging on this to find out whats happening here.

**Comment by maks** [comment]
Fixed by @democloid in #141.
