### ISSUE TITLE
Introduce more colour definitions

### ISSUE THREAD

**Issue by maks** [democloid/picoTracker#128]
I'd like to propose introducing more colour definitions. ie entries in the `ColorDefinition` enum in `View.h`.

Initially I would like to add the following:
* `CD_ERROR` for showing error messages or conditions, eg. the colour for the batt gauge when critically low level.
* `CD_WARN` for showing warning messages or conditions
* `CD_INFO` for show informational messages or conditions

My plan for warn and info is to initially use them as the colours for the base and middle parts of the "VU led bar" meters and error for the clipping range once I start working on the mixer screen PR again, so initial defaults of green, yellow and red for these three new colours respectively.

**Comment by democloid** [comment]
Totally fine. Main thing to keep in mind is that there are a total of 16 colors available per the driver, so need to use wisely and think a bit ahead. That can be expanded of course, at the cost of memory.

**Comment by maks** [comment]
Thanks for that @democloid ! And thanks for the pointer to the limitation on 16 colours, I didnt realise that 👍🏻
I can't think of any more colours I would want to add for now, but for sure need to add these strategically.

I'll start on a PR for this shortly.
