### ISSUE TITLE
can't access sample browser when preview is used quickly

### ISSUE THREAD

**Issue by paasukusai** [democloid/picoTracker#152]
Report
1. go to sample browser
2. double click to open sample browser
3. Repeat previewing various samples.
4. The preview will no longer play.(NG)
5. When I try to EXIT and reenter, the browser does not open.(NG)

https://youtu.be/4s93i91cqeY

It looks from 3/1
SHA-1: 58f6ab9785f84d38959f86c2c6192cd244ba34d9

samples
[drums.zip](https://github.com/democloid/picoTracker/files/14545493/drums.zip)
[Builds.zip](https://github.com/democloid/picoTracker/files/14545497/Builds.zip)

**Comment by maks** [comment]
Thanks for reporting this.
I have been able to reproduce it by downloading your drum samples and then trying to preview samples as rapidly as possible. Will need to investigate further to try to find whats causing it, likely some sort of race condition as the streaming code used for preview isn't used in any other part of the audio playback in picotracker.

**Comment by RAWJUNGLE** [comment]
+ freeze device, I've talked about this before. It's a critical error. It's impossible to work with.

**Comment by maks** [comment]
> + freeze device, I've talked about this before #66. It's a critical error. It's impossible to work with.

In my testing this issue does *not* cause a freeze of the device and matches the symptoms of the original report here.

**Comment by RAWJUNGLE** [comment]
> > + freeze device, I've talked about this before #66. It's a critical error. It's impossible to work with.
> 
> In my testing this issue does *not* cause a freeze of the device and matches the symptoms of the original report here.

If you have pre-loaded already samples and arranged them, then you run this problem, then you get a message about browser not being able to load, and if you try to save the project, you get a device freeze.

**Comment by maks** [comment]
> If you have pre-loaded already samples and arranged them, then you run this problem, then you get a message about browser not being able to load, and if you try to save the project, you get a device freeze.

Sure, but that is **not** what *this* issue is tracking.

**Comment by RAWJUNGLE** [comment]
> > If you have pre-loaded already samples and arranged them, then you run this problem, then you get a message about browser not being able to load, and if you try to save the project, you get a device freeze.
> 
> 
> 
> Sure, but that is **not** what *this* issue is tracking.
> 
> 

I mean, this bug will live on indefinitely.

If you run this issue from an issue and then try to save the project, you will get a freeze, I realize that these are two different issues, but can you check this in yourself and confirm the issue ?

**Comment by paasukusai** [comment]
I'm sorry for confuse you.
This issue is not about release version (only repository master).
I checked the source code and found where it happen, so this issue is from this month.

I think the sample browser is very difficult part to make, and  there are some problems.
Let's isolate the problems one by one and check them out.

**Comment by maks** [comment]
@paasukusai no all good, your report is very well done and it was easy to reproduce the issue. But I don't think the cause was the change to show file sizes unless you have tried a build before that commit and the issue does not occur there?

**Comment by RAWJUNGLE** [comment]
> @paasukusai no all good, your report is very well done and it was easy to reproduce the issue. But I don't think the cause was the change to show file sizes unless you have tried a build before that commit and the issue does not occur there?

Both problems exist in all versions, but it appears slightly less frequently than in this version.

**Comment by paasukusai** [comment]
Let me share the build removed the point.
This build seems ok.
(but sorry, I don't understand the source code yet..
If I find out anything more, I will share it.

[0309_mod.zip](https://github.com/democloid/picoTracker/files/14552528/0309_mod.zip)

**Comment by RAWJUNGLE** [comment]
https://youtu.be/bC5puw-J5Ek

**Comment by RAWJUNGLE** [comment]
@democloid

**Comment by democloid** [comment]
@maks I have reverted the show flash usage feature as it was clearly related to this. I've created #185 to track this

**Comment by maks** [comment]
@democloid yes all good. I'm not sure how its linked to the changes, I suspect maybe something to do with reading the filesizes from the sdcard, but I'll need to debug it properly. I'll try to get to it soon, as I find especially the filesize display if not the flash remaining an **invaluable** feature. I might try to tackle this as part of adding the FS in #171
