### ISSUE TITLE
Using SD card reader from tft display

### ISSUE THREAD

**Issue by ronaldsdc** [democloid/picoTracker#166]
Hello friends! Ronald here. Is there any chance or specific config to make the original prototype to detect sd card from the tft sd card reader?  Mine has spi connectors and i'm connecting them as gpio.h indicates but have no luck and have no separate sd card reader.  I also tried Speccery's version and it says no sd card detected.
Thanks for any help!!

![s-l1200](https://github.com/democloid/picoTracker/assets/107764576/753ee696-0997-47e4-a288-458972a3bdf4)

**Comment by democloid** [comment]
Should work, I may have tried it at some point but don't remember. One thing that might be happening is that those resistors may be limiting the bandwidth, so could work at lower frequency. Can you check what those resistors are?

Word of caution, this config, even if you make it work, may not be supported in the future. (We may switch to SDIO in the future)

**Comment by ronaldsdc** [comment]
Many thanks! that was the issue, they're 1k resistors, I tried bypassing them and it works now. Definitely gonna change to SDIO module in the future, but for now it worked superb, thank You!
