### ISSUE TITLE
cloning instrument causes system hang

### ISSUE THREAD

**Issue by djdiskmachine** [democloid/picoTracker#176]
Steps to reproduce:

    Go to Phrase View.
    Create a new sample instrument.
    Navigate to the instrument column.
    Use the clone command (L+B, A).

Expected: New instrument created with identical properties.

Result: System requires a hard reset.

Reocurrance: Always 

Commit: d1d4070

**Comment by djdiskmachine** [comment]
Something strange happens after InstrumentBank::Clone, line 256
That's as far as i managed to get 😅
It never returns anything valid and just hangs. More digging tomorrow

**Comment by maks** [comment]
Thanks for spotting this! I wonder why the change I did for the Midi VEL cmd caused this to break. Anyways thanks for reporting this, I can have a look at it later in the week if you don't get to it first 🙂

**Comment by djdiskmachine** [comment]
On closer inspection i'm mostly suspecting the 25+k savings commit but i'm not sure.

**Comment by djdiskmachine** [comment]
Fixed in https://github.com/djdiskmachine/picoTracker/commit/a0ce662404047c28b1b613e731aa254529ff34af

**Comment by maks** [comment]
Ah nice work @djdiskmachine ! 👍🏻 
Did you want to do a PR with that commit to this repo?
