### ISSUE TITLE
Browser pre-listen Bug

### ISSUE THREAD

**Issue by RAWJUNGLE** [democloid/picoTracker#192]
I also found the most likely problem. 
If the sd card is powered by spi, this is most likely the problem, the buffer is not keeping up with the active pre-listening. 
Maybe you need to invent something to make the buffer have time to clear the data during pre-listening. 
Maybe I am wrong in my conclusions, but the problem is somewhere here. 

https://github.com/democloid/picoTracker/issues/152
https://github.com/democloid/picoTracker/issues/66

**Comment by maks** [comment]
Can you please be specific about what exactly is the issue you are reporting? 
What version of the firmware are you seeing this on? 
What device hardware you are using? (standard picoTracker PCB or custom hardware?)

**Comment by RAWJUNGLE** [comment]
@maks You constantly ask me the same thing, but the problem exists in any case, no matter whether custom firmware or hardware or not, the problem exists, and it is wildly annoying, I think most users will support me in this. I understand perfectly well that you want to make new products, and on the global old problems do not have time, but can you at least fix this problem, because technically you can not do music in the tracker.

**Comment by democloid** [comment]
There's not enough information here to be able to debug anything and no willingness to provide such info. Please only open bug reports if you're willing to work with developers to solve the problem.

Plus it seems you reference already opened issues, so no need for an additional report on the same issue
