### ISSUE TITLE
battery display?

### ISSUE THREAD

**Issue by maks** [democloid/picoTracker#3]
With the portable edition PCB, I was trying to see if there was anything wired up to measure battery voltage and it looks like Pin 41 (GPIO_29_ADC3) is hooked up to do that with the R17/R18 voltage divider? so was wondering if you have changes in the firmware for measuring and some sort of calibration to then display that as a battery meter on screen?

**Comment by democloid** [comment]
Indeed, the battery voltage should be measurable. Unsure how precisely can the level be derived as it's not a linear function.
I haven't implemented this, but it should be pretty easy.

**Comment by maks** [comment]
Going to tag that I've started working on this as a number of people now have asked about it.
I don't expect to have particularly good battery % indications due to lipo flat discharge curve but Im now thinking some sort of UI indicator will be better than nothing.

**Comment by maks** [comment]
The initial implementation has been done in #127 with a follow-up to improve display at all times not just during playback in #130.

A final PR to use better colours for the battery gauge is still to come.

**Comment by maks** [comment]
Actually while I did do the PR to add colours for the battery gauge, I think I will keep this open until its also added to all screens as well as well as adding detection of usb being connected to be able to display a charging state as well.

**Comment by maks** [comment]
The colour work was done in #134
