### ISSUE TITLE
audio corruption after using "listen" button in sample browser

### ISSUE THREAD

**Issue by maks** [democloid/picoTracker#6]
Now the I have a portable built, I started experimenting with some basics (not even a proper track yet) and ran into an issue with sample import and playback.

I seem to not only get corrupted audio playback with using the `listen` button in the sample import browser (which I think @democloid  you've mentioned somewhere before as a known issue) but this then corrupts all subsequent audio playback in the current project until its reloaded or the device is reset (which of course is basically the same thing with the current device reset on project load). After a reset, if the problematic sample had been imported into the project, it plays back fine if placed into a track within the project.

I'll try to poke around and see if I can see where this is happening, at a first stab, I'd guess that maybe playing back using the sample preview code somehow corrupts the audio driver so that subsequent playback is incorrect. When I get the chance, I'll also try to upload here an example of a wave sample file that causes this for future reference.

**Comment by democloid** [comment]
Yes, this is a known issue (at least to me). There may be two issues at play here, so need to dig a bit deeper. As you say, if a project is reloaded after this issue, everything works fine, so it wasn't a blocker for "release" at the time.

I think it all boils down to memory issues. On one hand, I'm pretty sure I remember there being some memory leak that I couldn't pinpoint when loading samples (I fixed some tho), so the simple act going into the sample select menu would exhaust memory and corrupt audio playing.

On the other hand, there might be the issue of simply playing a sample also leaking memory or simply using too much and corrupting audio playing.

**Comment by maks** [comment]
Thanks for the pointer! I hadn't thought about it from a memory corruption point of view!
I'll start looking through the code next chance I get and see if I can spot any thing. For memory, I actually already had on my todo list that it would be useful to have that displayed for debug purposes but also I think showing Flash usage would be useful for end users as for example the Polyend Tracker has a "fuel gauge" type UI to show users how much memory space (I guess ram vs flash) they have left to use in each project, so I opened a [new issue to work on that too](https://github.com/democloid/picoTracker/issues/8).

**Comment by RAWJUNGLE** [comment]
What's the problem with using black pcb pico? 16mb flash, type-c usb.

**Comment by maks** [comment]
@RAWJUNGLE I'm seeing this on my build of the *portable* picoTracker which unlike the "desktop" version, uses the custom designed PCB which does have an external 16MB flash on it.

**Comment by maks** [comment]
@RAWJUNGLE oh, I just noticed you added that it has SPI sram as well, thats interesting! I had googled for boards usign a rp2040 with sram but haven't come across this one, would you have a link to the board you are referring too?
Though anyways, given the current custom PCB only has the 16MB of SPI flash on it, I think there is a need to get this fixed for running on the current boards.

**Comment by RAWJUNGLE** [comment]
@maks 
I was referring to adding an external sram. 

It doesn't matter which version you use, you can install them both.
A lot of people will make their own desktop version. I'm just making a recommendation.

You could also add a battery to the desktop version and do the same on the modules.

And for those who are technically savvy to work, you can build yourself a portable board.

**Comment by democloid** [comment]
@RAWJUNGLE The problem is that the pico doesn't provide an external memory interface, so an external device will not be memory mapped and to read from it you'd need to access it with SPI commands and presumably use some intermediate memory buffer to work on. It wouldn't provide much advantage than just reading from the SD card directly using the same method, except potentially some speed improvements, but that's not the main issue.

On the other hand, when I created the hardware and ported the software I wanted to go for pretty minimal and cheap hardware, which is more of a design decision rather than technical.

**Comment by democloid** [comment]
This should be solved via a972675217c52bea6679f978057b36b28b4988a8
