### ISSUE TITLE
Truncate long file sample names on Instrument screen

### ISSUE THREAD

**Issue by maks** [democloid/picoTracker#63]
Currently samples with long file names are shown with the full name wrapping to 2nd line instead of being truncated to only show as much as possible on 1 line.

**Comment by shockdesign** [comment]
Is there a sample picture of what it looks like when it wraps? I don't have the h/w to see..

**Comment by maks** [comment]
thanks for working on the @shockdesign !
Yes here is a photo of a too long sample name on the instrument screen and for extra reference the second photo is from the phrase screen as I just realised that it should also be fixed there too, but I'll open a separate issue for that.

![PXL_20240120_223941567](https://github.com/democloid/picoTracker/assets/71999/b7da13df-cdcd-4cbc-9352-3e32cbe25f1a)

![PXL_20240120_223931316](https://github.com/democloid/picoTracker/assets/71999/0da88938-f138-40d1-8ac0-057f029ec650)

**Comment by shockdesign** [comment]
@maks we should be able to close this issue now

**Comment by maks** [comment]
@shockdesign yes can do. 
Just for future reference, if you add to a PR's description `Fixes: #63` then when the PR is merged, it will automatically close the matching issue.
