### ISSUE TITLE
FX command to set velocity for MIDI instruments

### ISSUE THREAD

**Issue by maks** [democloid/picoTracker#79]
Currently there is a command to set volume for sample instruments but none to set the velocity for MIDI instruments.

We should either allow the current `VOLM` command to set the velocity of a MIDI instrument or introduce a new command to do that.

Suggested by @mikey303 via discord.

**Comment by maks** [comment]
Turns out that per https://github.com/democloid/picoTracker/blob/master/sources/Application/Instruments/MidiInstrument.cpp#L149 the `VOLM` command *does* already work with Midi instruments **BUT** it controls the CC 7 which is the "volume of the channel" which I think is not really what people would expect or want to do and instead would want to modify the velocity of the current note with this command.

**Comment by morbus123** [comment]
**Idea:** Combining MIDI velocity "aa" and gate time "bb" into a single command. 

_Additionally, I think it's pretty uncommon to send CC7-VOL for MIDI sequencing; maybe it's to keep sample and MIDI tracks consistent. In my experience, CC7 is used for the volume of the whole track and velocity for accenting notes._
